version: "3.8"

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "8080:80"          # Main entrypoint
      - "8081:8081"        # Traefik dashboard
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock

  backend-v1:
    build: ./backend-v1
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend-v1.loadbalancer.server.port=8080"

  backend-v2:
    build: ./backend-v2
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend-v2.loadbalancer.server.port=8080"
