http:
  routers:
    blue-green-router:
      rule: "Host(`localhost`)"
      service: blue-green-service
      entrypoints:
        - web

  services:
    blue-green-service:
      weighted:
        services:
          - name: backend-v1@docker
            weight: 8
          - name: backend-v2@docker
            weight: 2